Issue 7
andymeneely/dev-fortress-server pull request #19
Opened 2017-03-05 21:39 UTC by DanSwtmn

In the event tests, there is a commented out test that is not working for some reason even though I can get a response from testing the endpoint manually. Also with the updateEventById() I believe that you should be able to edit all fields and not only specific ones.

2017-03-07 15:29 UTC, ShaydeNofziger requested changes

2017-03-07 15:29 UTC, ShaydeNofziger commented on app/routes/event.js
> +  eventController.createEvent
Should this be `updateEvent`?

2017-03-07 15:29 UTC, ShaydeNofziger commented on migrations/20160912145044_setup.js
> +    table.boolean('disabled').notNullable();
To match the data model schema, (bool not required) we should default this to `false`.

2017-03-07 16:29 UTC, DanSwtmn commented on migrations/20160912145044_setup.js
> +    table.boolean('disabled').notNullable();
Changed

2017-03-07 16:29 UTC, DanSwtmn commented on app/routes/event.js
> +  eventController.createEvent
Yes you are correct i did change it

2017-03-08 20:39 UTC, ShaydeNofziger approved these changes

2017-03-08 20:39 UTC, merged